name: coverage
on:
    push:
        branches:
            - main
            - coverage

jobs:
    scrutinizer:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: |
                    mkdir -p build/logs
                    vendor/bin/phpunit --coverage-clover=coverage.clover

            -   name: Export
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
