name: phpunit
on: [ push, pull_request ]

jobs:
    laravel_54:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.4.*" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:~5.7
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_55:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.5.*" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:~6.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_56:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.6.*" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:~7.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_57:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.7.*" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:~7.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_58:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.8.*" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:^8.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_6x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4", "8.0" ]
                laravel: [ "^6.0" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }} phpunit/phpunit:^8.3
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_7x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4", "8.0" ]
                laravel: [ "^7.0" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }}
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_8x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "^8.0" ]
                support: [ "2.0", "3.0", "4.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}, Support ${{ matrix.support }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: none

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} andrey-helldar/support:^${{ matrix.support }}
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
