name: phpunit
on: [ push ]

jobs:
    laravel_54:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.4.*" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug
                    ini-values: xdebug.mode=coverage

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:~5.7
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_55:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.5.*" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:~6.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_56:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.6.*" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:~7.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_57:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.7.*" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:~7.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_58:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4" ]
                laravel: [ "5.8.*" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:^8.0
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_6x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4", "8.0" ]
                laravel: [ "^6.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }} phpunit/phpunit:^8.3
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_7x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.2", "7.3", "7.4", "8.0" ]
                laravel: [ "^7.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }}
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    laravel_8x:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "^8.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:${{ matrix.laravel }}
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit

    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: |
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: |
                    mkdir -p build/logs
                    vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
